.compile-ra: &compile_template
  script:
    - mkdir -p build
    - cd build
    - cmake -GNinja ..
    - cmake --build .
  stage: build
  cache:
    # Increase the number in the cache key to start with
    # a fresh build cache. This is only useful in case of
    # build system bug and/or updates of ExternalProjects!
    key: "$CI_JOB_NAME-2"
    paths:
      - build/
  artifacts:
    paths:
      - build/bin/
    expire_in: 1 day

compile-ra:
  <<: *compile_template
  except:
    - schedules

.test: &test_template
  script:
    - "echo running test \"$TEST_PATTERN\""
    - "cd build"
    - "cmake -GNinja .."
    - "ctest --output-on-failure -R \"$TEST_PATTERN\""
  stage: test
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - build/
  variables:
    TEST_PATTERN: "."

tests:
  <<: *test_template
  dependencies:
    - compile-ra
  except:
    - schedules


.compile-ra-schedule: &compile_schedule
  <<: *compile_template
  only:
    - schedules

compile-ra-16.04:
  <<: *compile_schedule
  image: ubuntu-16.04

compile-ra-18.04:
  <<: *compile_schedule
  image: ubuntu-18.04

compile-ra-18.04-no-v8:
  <<: *compile_schedule
  image: ubuntu-18.04-no-v8


.test-schedule: &test_schedule
  <<: *test_template
  only:
    - schedules

tests-16.04:
  <<: *test_schedule
  dependencies:
    - compile-ra-16.04

tests-18.04:
  <<: *test_schedule
  dependencies:
    - compile-ra-18.04

tests-18.04-no-v8:
  <<: *test_schedule
  dependencies:
    - compile-ra-18.04-no-v8
