stages:
  - build
  - test
  - memcheck

.compile-ra: &compile_template
  script:
    - mkdir -p build
    - cd build
    - cmake -GNinja ..
    # limit average load to enforce some load distribution between different ninja instances
    - cmake --build . -- -l $(( $(nproc) * 3 / 2))
  stage: build
  cache:
    # Increase the number in the cache key to start with
    # a fresh build cache. This is only useful in case of
    # build system bug and/or updates of ExternalProjects!
    key: "$CI_JOB_NAME-2"
    paths:
      - build/
  artifacts:
    paths:
      - build/bin/
    expire_in: 1 day

compile-ra:
  <<: *compile_template
  except:
    - schedules

.test: &test_template
  script:
    - "sh strategy/typescript/setup.sh"
    - "echo running test \"$TEST_PATTERN\""
    - "cd build"
    - "cmake -GNinja .."
    - "ctest --output-on-failure -R \"$TEST_PATTERN\""
  stage: test
  cache:
    # Increase the number in the cache key to start with
    # a fresh build cache. This is only useful in case of
    # build system bug and/or updates of ExternalProjects!
    key: "$CI_JOB_NAME-2"
    paths:
      - build/
  variables:
    TEST_PATTERN: "."

sanitize:
  script:
    - "mkdir -p build"
    - "cd build"
    - "cmake -GNinja -DCMAKE_CXX_FLAGS=\"-fsanitize=address\" -DCMAKE_BUILD_TYPE=Debug .."
    - "cmake --build . --target check -- -l $(( $(nproc) * 3 / 2))"
  stage: memcheck
  cache:
    # Increase the number in the cache key to start with
    # a fresh build cache. This is only useful in case of
    # build system bug and/or updates of ExternalProjects!
    key: "$CI_JOB_NAME"
    paths:
      - build/
  except:
    - schedules
  dependencies: []


tests:
  <<: *test_template
  dependencies:
    - compile-ra
  except:
    - schedules


.compile-ra-schedule: &compile_schedule
  <<: *compile_template
  only:
    - schedules

compile-ra-16.04:
  <<: *compile_schedule
  image: ubuntu-16.04

compile-ra-18.04:
  <<: *compile_schedule
  image: ubuntu-18.04

compile-ra-18.04-no-v8:
  <<: *compile_schedule
  image: ubuntu-18.04-no-v8


.test-schedule: &test_schedule
  <<: *test_template
  only:
    - schedules

tests-16.04:
  <<: *test_schedule
  image: ubuntu-16.04
  dependencies:
    - compile-ra-16.04

tests-18.04:
  <<: *test_schedule
  image: ubuntu-18.04
  dependencies:
    - compile-ra-18.04

tests-18.04-no-v8:
  <<: *test_schedule
  image: ubuntu-18.04-no-v8
  dependencies:
    - compile-ra-18.04-no-v8
