compile-ra:
  script:
    - mkdir -p build
    - cd build
    - cmake -GNinja ..
    - cmake --build .
  stage: build
  cache:
    key: "default"
    paths:
      - build/
  artifacts:
    paths:
      - build/bin/
    expire_in: 1 day

.test: &test_template
  script:
    - "echo running test \"$TEST_PATTERN\""
    - "cd build"
    - "cmake -GNinja .."
    - "ctest --output-on-failure -R \"$TEST_PATTERN\""
  stage: test
  cache:
    key: "tests"
    paths:
      - build/

tests:
  <<: *test_template
  variables:
    TEST_PATTERN: "."
