compile-ra:
  script:
    - mkdir -p build
    - cd build
    - cmake -GNinja ..
    - cmake --build .
  stage: build
  cache:
    paths:
      - build/
  artifacts:
    paths:
      - build/bin/
    expire_in: 1 day

.luacheck: &luacheck_template
  script:
    - "echo running luacheck for $CHECK_PATH"
    - "cd $CHECK_PATH"
    - "luacheck -q ."
  stage: test
  when: always
  dependencies: []

luacheck-base:
  <<: *luacheck_template
  variables:
    CHECK_PATH: strategy/base
